
FROM continuumio/anaconda3:2020.07

WORKDIR /analyzer/app

RUN conda create -n estnltk python=3.5 anaconda

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "estnltk", "/bin/bash", "-c"]

RUN conda install -c estnltk -c conda-forge estnltk
RUN conda install -c anaconda pandas scipy matplotlib numpy networkx spacy scikit-learn gensim

RUN conda env list

#ADD app /analyzer/app

ENV NB_PREFIX=/analyzer/app

ENTRYPOINT ["jupyter", "-u", "--allow-root", "--no-browser", "--notebook-dir=/analyzer/app", "--ip=0.0.0.0", "--NotebookApp.password=''", "--NotebookApp.allow_origin='*'", "notebook"]
